// AUTO-GENERATED by scripts/native/apply-brand.mjs — do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

import Foundation

enum Brand {
    static let name = "heron"
    static let displayName = "Heron"
    static let bundleId = "com.heron.app"
    static let appGroup = "group.com.heron.app"
    static let urlScheme = "heron"
    static let serviceType = "_heron._tcp"
    static let spotlightDomain = "com.heron.app.jobs"
    static let keychainService = "com.heron.app"
    static let openJobActivityType = "com.heron.app.openJob"
    /// Capacitor JS↔Swift bridge name. Must match TS registerPlugin('...') call.
    static let capacitorPluginName = "HeronNative"

    /// UserDefaults keys — all prefixed with brand name so they're
    /// namespaced and a brand rename moves them cleanly.
    enum DefaultsKey {
        static let lanUrl = "\(Brand.name):lan-url"
        static let backendResolvedUrl = "\(Brand.name):backend-resolved-url"
        static let tailscaleUrl = "\(Brand.name):tailscale-url"
        static let productionUrl = "\(Brand.name):production-url"
        static let lastSeenIssue = "\(Brand.name):last-seen-issue"
        /// Bearer token mirrored from the WebView into App Group
        /// UserDefaults so the Share Extension can attach
        /// Authorization: Bearer <token> on its POSTs. Set by
        /// NativePlugin.setSharedBearerToken; cleared on
        /// sign-out.
        static let bearerToken = "\(Brand.name):bearer-token"
    }

    /// Build a custom-scheme deep link.
    static func deepLink(_ route: String) -> String {
        let trimmed = route.hasPrefix("/") ? String(route.dropFirst()) : route
        return "\(urlScheme)://\(trimmed)"
    }
    static func jobDeepLink(_ jobId: String) -> String {
        return "\(urlScheme)://job/\(jobId)"
    }
}
