// AUTO-GENERATED by scripts/native/apply-brand.mjs — do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

/**
 * Single source of truth for brand identifiers — read at runtime/build.
 * Web client, Capacitor iOS bundle, and Electron WebView all import
 * from this file so a brand rename touches one JSON file.
 */
export const BRAND = {
  name: "career-ops",
  displayName: "Career Ops",
  tagline: "Run your job search like a product launch.",
  bundleId: "com.resistjs.careerops",
  appGroup: "group.com.resistjs.careerops",
  urlScheme: "careerops",
  serviceType: "_career-ops._tcp",
  mdnsType: "career-ops",
  spotlightDomain: "com.resistjs.careerops.jobs",
  keychainService: "com.resistjs.careerops",
  colors: {
    "primary": "#5b6cff",
    "accentEmeraldLight": "#34d399",
    "accentEmeraldDark": "#10b981",
    "darkBg": "#0a0a0b",
    "darkSurface": "#18181b",
    "lightOnDark": "#e4e4e7"
  },
  repo: {
    "owner": "kaelys-js",
    "name": "career-ops",
    "url": "https://github.com/kaelys-js/career-ops",
    "issues": "https://github.com/kaelys-js/career-ops/issues",
    "docs": "https://github.com/kaelys-js/career-ops#readme",
    "upstream": "https://github.com/santifer/career-ops"
  },
} as const;

/** Build a custom-scheme deep link for a job. */
export function jobDeepLink(jobId: string): string {
  return `${BRAND.urlScheme}://job/${jobId}`;
}

/** Build a custom-scheme deep link for any in-app route. */
export function deepLink(route: string): string {
  return `${BRAND.urlScheme}://${route.replace(/^\//, '')}`;
}

/** Brand-namespaced DOM event names. Use these on both sides of
 * window.dispatchEvent + window.addEventListener — same source of
 * truth means a rename can never split the listener from the
 * dispatcher. */
export const BRAND_EVENTS = {
  openNotifications: `${BRAND.name}:open-notifications`,
  notify: `${BRAND.name}:notify`,
} as const;

/** Brand-namespaced localStorage key prefix. Use as
 * `${BRAND_STORAGE_PREFIX}:my-key` so user state for one
 * brand can't collide with another fork on the same machine. */
export const BRAND_STORAGE_PREFIX = BRAND.name;
