// AUTO-GENERATED by scripts/native/apply-brand.mjs — do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

/**
 * Single source of truth for brand identifiers — read at runtime/build.
 * Web client, Capacitor iOS bundle, and Electron WebView all import
 * from this file so a brand rename touches one JSON file.
 */
export const BRAND = {
  name: "heron",
  displayName: "Heron",
  tagline: "Stand still. Strike well.",
  bundleId: "com.heron.app",
  appGroup: "group.com.heron.app",
  urlScheme: "heron",
  serviceType: "_heron._tcp",
  mdnsType: "heron",
  spotlightDomain: "com.heron.app.jobs",
  keychainService: "com.heron.app",
  capacitorPluginName: "HeronNative",
  colors: {
    "$comment": "Colors stay on the legacy career-ops palette until Task 10 — the new Heron tokens (Slate #4a5b6d, Dawn #c89b4a, Reed #7a8c6d, warm-paper #f7f5f0, etc.) ship together with ui/src/app.css token wiring and the component-level color sweep. Task 10 will replace this entire block.",
    "primary": "#5b6cff",
    "accentEmeraldLight": "#34d399",
    "accentEmeraldDark": "#10b981",
    "darkBg": "#0a0a0b",
    "darkSurface": "#18181b",
    "lightOnDark": "#e4e4e7"
  },
  repo: {
    "owner": "heron",
    "name": "heron",
    "url": "https://github.com/heron/heron",
    "issues": "https://github.com/heron/heron/issues",
    "docs": "https://github.com/heron/heron#readme",
    "upstream": "https://github.com/santifer/career-ops"
  },
} as const;

/** Build a custom-scheme deep link for a job. */
export function jobDeepLink(jobId: string): string {
  return `${BRAND.urlScheme}://job/${jobId}`;
}

/** Build a custom-scheme deep link for any in-app route. */
export function deepLink(route: string): string {
  return `${BRAND.urlScheme}://${route.replace(/^\//, '')}`;
}

/** Brand-namespaced DOM event names. Use these on both sides of
 * window.dispatchEvent + window.addEventListener — same source of
 * truth means a rename can never split the listener from the
 * dispatcher. */
export const BRAND_EVENTS = {
  openNotifications: `${BRAND.name}:open-notifications`,
  notify: `${BRAND.name}:notify`,
} as const;

/** Brand-namespaced localStorage key prefix. Use as
 * `${BRAND_STORAGE_PREFIX}:my-key` so user state for one
 * brand can't collide with another fork on the same machine. */
export const BRAND_STORAGE_PREFIX = BRAND.name;

/** Named localStorage keys used across the app. Centralised so a
 * rebrand (BRAND.name change) automatically retargets every read
 * + write. Use these constants instead of typing literal
 * '${BRAND.name}:authed' strings around the codebase — keeps the
 * key names in one searchable place AND eliminates the drift
 * where one site reads 'career-ops:authed' and another writes
 * 'careerops:authed' or similar. */
export const BRAND_STORAGE_KEYS = {
  /** '1' iff the user has a live local-auth marker — used by the
   * layout boot path for the sync-bounce-to-/login race. */
  authed: `${BRAND.name}:authed`,
  /** Bearer token captured from better-auth's Set-Auth-Token
   * header. Required for the Capacitor WebView (cookies don't
   * cross from careerops:// to http://) and mirrored into App
   * Group for the Share Extension. */
  bearerToken: `${BRAND.name}:bearer-token`,
  /** User-chosen theme ('light' | 'dark' | 'system'). Read by
   * app.html's inline bootstrap script for FOUC-free initial paint. */
  theme: `${BRAND.name}:theme`,
  /** Quiet-hours preference JSON ({enabled, startHour, endHour}). */
  quietHours: `${BRAND.name}:quiet-hours`,
  /** Per-component collapse/expand state — namespaced under the
   * brand prefix so CollapsibleCard / CollapsibleGroup / similar
   * never collide with unrelated apps on the same origin. */
  collapseCardPrefix: `${BRAND.name}:cc`,
  collapseGroupPrefix: `${BRAND.name}:cg`,
  /** Push-notifications opt-in level prefs (Notification API). */
  pushPrefs: `${BRAND.name}:push-prefs`,
} as const;
