import Foundation
import Combine
import WatchConnectivity
import WidgetKit

/**
 * WatchModel — single source of truth for the watch UI.
 *
 * Holds the same data shape the iPhone widgets read out of the App
 * Group. Updates arrive through three channels (in priority order):
 *
 *   1. WCSession messages from the iPhone (push, ~real-time)
 *   2. App Group UserDefaults written by the phone (used when the
 *      phone is unreachable; same defaults the iPhone widgets use)
 *   3. Empty / placeholder data for first-launch on the watch
 *
 * The `@MainActor @Published` properties drive the UI directly; views
 * just bind to them.
 */
@MainActor
final class WatchModel: NSObject, ObservableObject, WCSessionDelegate {
    static let shared = WatchModel()

    @Published var stats: Stats = .empty
    @Published var nextInterview: InterviewSnapshot?
    @Published var topApply: ApplyCandidate?
    @Published var openIssues: [IssueSnapshot] = []
    @Published var lastSyncAt: Date?
    @Published var isReachable: Bool = false
    /// Watch app's auth gate. TRUE means the paired iPhone has an active
    /// Better-Auth session AND has pushed at least one widget update to
    /// the App Group (via CareerOpsNativePlugin.updateWidgets, which now
    /// stamps `auth:isAuthenticated` into the same defaults the Watch
    /// reads). Default FALSE — first-launch / signed-out / never-paired
    /// Watches show a "Sign in on iPhone" gate instead of empty data.
    @Published var isAuthenticated: Bool = false

    // Sourced from Brand.swift (auto-generated by apply-brand.mjs from
    // branding/brand.json). Was hardcoded "group.com.resistjs.careerops"
    // which would silently drift on rebrand — the host app would write
    // to the new App Group while the Watch kept reading from the old.
    private let appGroupId = Brand.appGroup

    struct Stats: Codable {
        var queued: Int = 0
        var appliedToday: Int = 0
        var upcomingInterviews: Int = 0
        static let empty = Stats()
    }
    struct InterviewSnapshot: Codable {
        var jobId: String
        var company: String
        var role: String
        var stage: String
        var scheduledAt: Date
        var interviewers: [String]
    }
    struct ApplyCandidate: Codable {
        var jobId: String
        var company: String
        var role: String
        var score: Double
        var compBand: String?
        var location: String?
        var portal: String?
    }
    struct IssueSnapshot: Codable {
        var id: String
        var severity: String
        var source: String
        var summary: String
        var ts: Double
    }

    // MARK: - Lifecycle

    func bootstrap() {
        // Activate WCSession if the watch is paired with an iPhone that
        // has the companion app installed.
        if WCSession.isSupported() {
            let session = WCSession.default
            session.delegate = self
            session.activate()
            isReachable = session.isReachable
        }
        // First paint comes from whatever the phone last pushed into the
        // App Group defaults. Subsequent WCSession messages overwrite.
        loadFromDefaults()
    }

    // MARK: - WCSessionDelegate

    nonisolated func session(
        _ session: WCSession,
        activationDidCompleteWith state: WCSessionActivationState,
        error: Error?
    ) {
        // No-op; the activation callback exists so didReceiveMessage works.
    }

    nonisolated func sessionReachabilityDidChange(_ session: WCSession) {
        let reachable = session.isReachable
        Task { @MainActor in self.isReachable = reachable }
    }

    nonisolated func session(
        _ session: WCSession,
        didReceiveMessage message: [String: Any],
        replyHandler: @escaping ([String: Any]) -> Void
    ) {
        Task { @MainActor in
            self.applyPayload(message)
            self.lastSyncAt = Date()
            replyHandler(["ok": true])
            WidgetCenter.shared.reloadAllTimelines()
        }
    }

    nonisolated func session(
        _ session: WCSession,
        didReceiveApplicationContext context: [String: Any]
    ) {
        Task { @MainActor in
            self.applyPayload(context)
            self.lastSyncAt = Date()
            WidgetCenter.shared.reloadAllTimelines()
        }
    }

    // MARK: - Data merge

    func applyPayload(_ payload: [String: Any]) {
        // Auth state — iPhone explicitly pushes `authenticated: true`
        // after a successful sign-in (and `false` after sign-out). Treat
        // ANY widget push from the iPhone as proof of an active iPhone
        // session unless `authenticated` is explicitly false, because the
        // iPhone-side plugin only calls updateWidgets when an
        // authenticated route has data to show.
        if let auth = payload["authenticated"] as? Bool {
            isAuthenticated = auth
            // Scrub local data when the iPhone reports signed-out so a
            // screenshot of the Watch face never leaks queue / interview
            // info after the user signed out on the phone.
            if !auth {
                stats = .empty
                nextInterview = nil
                topApply = nil
                openIssues = []
            }
        } else {
            // No explicit flag → infer from data presence. Receiving a
            // payload at all means the iPhone is paired + the iPhone-side
            // app is running an authenticated session.
            isAuthenticated = true
        }
        if let s = payload["stats"] as? [String: Int] {
            stats = Stats(
                queued: s["queued"] ?? stats.queued,
                appliedToday: s["appliedToday"] ?? stats.appliedToday,
                upcomingInterviews: s["upcomingInterviews"] ?? stats.upcomingInterviews
            )
        }
        if let blob = payload["nextInterview"] as? [String: Any] {
            nextInterview = decode(InterviewSnapshot.self, from: blob)
        } else if payload.keys.contains("nextInterview") {
            nextInterview = nil
        }
        if let blob = payload["topApply"] as? [String: Any] {
            topApply = decode(ApplyCandidate.self, from: blob)
        } else if payload.keys.contains("topApply") {
            topApply = nil
        }
        if let arr = payload["openIssues"] as? [[String: Any]] {
            openIssues = arr.compactMap { decode(IssueSnapshot.self, from: $0) }
        }
        persistToDefaults()
    }

    // MARK: - Cross-launch persistence

    private func loadFromDefaults() {
        guard let defaults = UserDefaults(suiteName: appGroupId) else { return }
        // Auth gate — defaults to FALSE so a fresh-installed Watch app
        // (no data ever pushed) shows the sign-in gate immediately rather
        // than an empty Stats(0, 0, 0) page that looks like a working app.
        isAuthenticated = defaults.bool(forKey: "auth:isAuthenticated")
        stats = Stats(
            queued: defaults.integer(forKey: "stats:queued"),
            appliedToday: defaults.integer(forKey: "stats:appliedToday"),
            upcomingInterviews: defaults.integer(forKey: "stats:upcomingInterviews")
        )
        if let d = defaults.data(forKey: "interview:next"),
           let snap = try? JSONDecoder().decode(InterviewSnapshot.self, from: d) {
            nextInterview = snap
        }
        if let d = defaults.data(forKey: "topApply:next"),
           let snap = try? JSONDecoder().decode(ApplyCandidate.self, from: d) {
            topApply = snap
        }
        if let d = defaults.data(forKey: "issues:open"),
           let arr = try? JSONDecoder().decode([IssueSnapshot].self, from: d) {
            openIssues = arr
        }
    }

    private func persistToDefaults() {
        guard let defaults = UserDefaults(suiteName: appGroupId) else { return }
        defaults.set(isAuthenticated, forKey: "auth:isAuthenticated")
        defaults.set(stats.queued, forKey: "stats:queued")
        defaults.set(stats.appliedToday, forKey: "stats:appliedToday")
        defaults.set(stats.upcomingInterviews, forKey: "stats:upcomingInterviews")
        if let n = nextInterview, let d = try? JSONEncoder().encode(n) {
            defaults.set(d, forKey: "interview:next")
        } else {
            defaults.removeObject(forKey: "interview:next")
        }
        if let t = topApply, let d = try? JSONEncoder().encode(t) {
            defaults.set(d, forKey: "topApply:next")
        } else {
            defaults.removeObject(forKey: "topApply:next")
        }
        if let d = try? JSONEncoder().encode(openIssues) {
            defaults.set(d, forKey: "issues:open")
        }
    }

    // MARK: - JSON dictionary decode helper

    private func decode<T: Decodable>(_ type: T.Type, from dict: [String: Any]) -> T? {
        guard let data = try? JSONSerialization.data(withJSONObject: dict) else { return nil }
        return try? JSONDecoder().decode(T.self, from: data)
    }
}
