// BrandTest -- validates the auto-generated Brand.kt constants match
// the values in branding/brand.json. Brand.kt itself is excluded from
// JaCoCo coverage (it's generated by apply-brand.mjs), but the
// constants it exposes drive every other Android subsystem -- so a
// canary test ensures the apply-brand pipeline produced something
// sensible.
//
// Mirrors AppTests/BrandTests.swift on the iOS side.

package com.resistjs.heron

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class BrandTest {
    @Test
    fun `bundle identifiers are non-empty`() {
        assertTrue(Brand.name.isNotEmpty())
        assertTrue(Brand.displayName.isNotEmpty())
        assertTrue(Brand.bundleId.isNotEmpty())
        assertTrue(Brand.urlScheme.isNotEmpty())
        assertTrue(Brand.serviceType.isNotEmpty())
        assertTrue(Brand.keychainService.isNotEmpty())
    }

    @Test
    fun `bundleId follows reverse-DNS pattern`() {
        // Must be at least two dot-separated segments (e.g. com.resistjs.heron).
        assertTrue(Brand.bundleId.contains("."))
        assertTrue(Brand.bundleId.split(".").size >= 2)
    }

    @Test
    fun `urlScheme is a single lowercase token`() {
        assertEquals(Brand.urlScheme, Brand.urlScheme.lowercase())
        assertFalse(Brand.urlScheme.contains("."))
        assertFalse(Brand.urlScheme.contains("/"))
        assertFalse(Brand.urlScheme.contains(" "))
    }

    @Test
    fun `serviceType follows mDNS service-type pattern`() {
        // mDNS service types are `_<name>._tcp` or `_<name>._udp`.
        assertTrue(Brand.serviceType.startsWith("_"))
        assertTrue(Brand.serviceType.endsWith("._tcp") || Brand.serviceType.endsWith("._udp"))
    }

    @Test
    fun `PrefsKey values are brand-namespaced`() {
        // Every key starts with the brand name to keep
        // SharedPreferences cross-brand-safe in fork scenarios.
        val keys =
            listOf(
                Brand.PrefsKey.lanUrl,
                Brand.PrefsKey.backendResolvedUrl,
                Brand.PrefsKey.tailscaleUrl,
                Brand.PrefsKey.productionUrl,
                Brand.PrefsKey.lastSeenIssue,
                Brand.PrefsKey.errorQueue,
                Brand.PrefsKey.online,
            )
        for (key in keys) {
            assertTrue("$key should start with brand name", key.startsWith(Brand.name))
        }
    }

    @Test
    fun `PrefsKey values are unique`() {
        val keys =
            listOf(
                Brand.PrefsKey.lanUrl,
                Brand.PrefsKey.backendResolvedUrl,
                Brand.PrefsKey.tailscaleUrl,
                Brand.PrefsKey.productionUrl,
                Brand.PrefsKey.lastSeenIssue,
                Brand.PrefsKey.errorQueue,
                Brand.PrefsKey.online,
            )
        assertEquals("PrefsKey values should be unique", keys.size, keys.toSet().size)
    }

    @Test
    fun `deepLink prepends url scheme`() {
        val link = Brand.deepLink("inbox")
        assertEquals("${Brand.urlScheme}://inbox", link)
    }

    @Test
    fun `deepLink strips leading slash from route`() {
        val link = Brand.deepLink("/inbox")
        assertEquals("${Brand.urlScheme}://inbox", link)
        assertFalse(link.contains("///"))
    }

    @Test
    fun `deepLink handles empty route as scheme root`() {
        val link = Brand.deepLink("")
        assertEquals("${Brand.urlScheme}://", link)
    }

    @Test
    fun `deepLink handles routes with query strings`() {
        val link = Brand.deepLink("job/123?source=widget")
        assertEquals("${Brand.urlScheme}://job/123?source=widget", link)
    }

    @Test
    fun `jobDeepLink builds the canonical job route`() {
        val link = Brand.jobDeepLink("abc-123")
        assertEquals("${Brand.urlScheme}://job/abc-123", link)
    }

    @Test
    fun `jobDeepLink with empty jobId still produces a parseable URL`() {
        val link = Brand.jobDeepLink("")
        assertEquals("${Brand.urlScheme}://job/", link)
    }
}
