<script lang="ts">
  /**
   * Signup page — invite-code-based onboarding.
   *
   * Two modes (driven by +page.server.ts):
   *   • First-user (no users in DB): becomes the OWNER. Name + email
   *     + passkey enrollment — no invite code required.
   *   • Invite-required: 6-digit invite code (generated by an existing
   *     owner) + name + email + passkey. We POST the code to
   *     /api/auth/invite/claim before the WebAuthn ceremony so the user
   *     doesn't get a half-baked account if the code is invalid.
   *
   * Design: mirrors the login page (hero brand mark, gradient bloom bg,
   * glassy card, h-12 primary action) plus a top-left chevron-back link
   * to /login so users who tapped "Set up with invite code" by mistake
   * have an obvious escape hatch. Better Auth's passkey plugin handles
   * the actual WebAuthn ceremony; on success we redirect to /onboarding.
   */
  import { authClient } from '$lib/client/auth-client';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Label } from '$lib/components/ui/label';
  import { KeyRound, AlertCircle, ChevronLeft, ShieldCheck } from '@lucide/svelte';
  import { goto } from '$app/navigation';
  import { APP_NAME } from '$lib/config/branding';

  let { data } = $props<{
    data: { isFirstUser: boolean; githubEnabled: boolean };
  }>();

  let name = $state('');
  let email = $state('');
  let inviteCode = $state('');
  let busy = $state(false);
  let error = $state<string | null>(null);

  /**
   * Translate raw signup / WebAuthn / API errors into friendly copy.
   * Mirrors the login page's friendlyAuthError() helper so the auth
   * surface is consistent across both screens.
   */
  function friendlyError(raw: unknown, fallback = 'Account creation failed.'): string {
    const msg =
      raw instanceof Error
        ? raw.message
        : typeof raw === 'string'
          ? raw
          : raw && typeof raw === 'object' && 'message' in raw
            ? String((raw as { message: unknown }).message ?? '')
            : '';
    const lower = msg.toLowerCase();

    if (
      lower.includes('cancel') ||
      lower.includes('aborted') ||
      lower.includes('notallowed') ||
      lower.includes('not allowed') ||
      lower.includes('timed out') ||
      lower.includes('timeout')
    ) {
      return "Passkey setup was cancelled. Tap Create again when you're ready — your device prompt should appear.";
    }
    if (lower.includes('not supported') || lower.includes('unsupported')) {
      return 'Passkeys are not supported on this device. Try Safari (iOS) or a recent Chrome / Firefox.';
    }
    if (lower.includes('network') || lower.includes('fetch')) {
      return "Couldn't reach the sign-up server. Check your connection and try again.";
    }
    if (lower.includes('invite') && lower.includes('used')) {
      return 'That invite code has already been used. Ask the owner to issue a new one.';
    }
    if (lower.includes('invite') && (lower.includes('invalid') || lower.includes('not found'))) {
      return "We couldn't find that invite code. Double-check the digits with whoever invited you.";
    }
    if (lower.includes('email') && lower.includes('exist')) {
      return 'An account with that email already exists. Sign in instead?';
    }
    if (!msg) return fallback;
    return msg;
  }

  async function createAccount() {
    error = null;
    if (!name.trim()) {
      error = 'Please enter your name.';
      return;
    }
    if (!email.trim() || !email.includes('@')) {
      error = 'Please enter a valid email address.';
      return;
    }
    if (!data.isFirstUser && !/^\d{6}$/.test(inviteCode.trim())) {
      error = 'Invite code must be 6 digits.';
      return;
    }

    busy = true;
    try {
      // For non-first users, validate the invite code first so we don't
      // create a half-baked account before realising the code is bad.
      if (!data.isFirstUser) {
        const claim = await fetch('/api/auth/invite/claim', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code: inviteCode.trim(), email: email.trim() }),
        });
        if (!claim.ok) {
          const body = await claim.json().catch(() => null);
          error = friendlyError(body?.error?.message, 'Invite code not accepted.');
          busy = false;
          return;
        }
      }

      // Create the account via passkey. Better Auth's plugin will:
      //   1. Generate WebAuthn options
      //   2. Trigger the browser's passkey UI
      //   3. Persist the new user + credential
      //   4. Set the session cookie
      const result = await authClient.signUp.email({
        email: email.trim(),
        password: crypto.randomUUID(), // unused — emailAndPassword is disabled
        name: name.trim(),
      });

      if (result?.error) {
        error = friendlyError(result.error);
        busy = false;
        return;
      }

      // Immediately enroll a passkey for the new account.
      const pk = await authClient.passkey.addPasskey({
        name: name.trim() + "'s passkey",
      });
      if (pk?.error) {
        error = friendlyError(pk.error, 'Account created, but passkey setup failed.');
        busy = false;
        return;
      }

      await goto('/onboarding', { invalidateAll: true });
    } catch (e) {
      error = friendlyError(e);
      busy = false;
    }
  }
</script>

<svelte:head>
  <title>Set up account — {APP_NAME}</title>
</svelte:head>

<main
  class="relative flex min-h-svh flex-col items-center justify-center overflow-hidden bg-background px-6 py-12"
>
  <!-- Brand bloom — same gradient as /login + boot-fallback so the
       three-step entry flow (boot → login → signup) feels like one
       continuous visual surface. -->
  <div
    aria-hidden="true"
    class="pointer-events-none absolute inset-0 overflow-hidden"
    style="background:
      radial-gradient(60rem 40rem at 50% -10%, rgba(139, 92, 246, 0.22), transparent 60%),
      radial-gradient(40rem 30rem at 100% 100%, rgba(99, 102, 241, 0.14), transparent 60%),
      radial-gradient(36rem 28rem at 0% 100%, rgba(168, 85, 247, 0.12), transparent 60%);"
  ></div>

  <!-- Top-left BACK button — fixed, always-visible escape hatch. Tapping
       returns the user to /login (the only realistic place they came
       from). Position uses pt-safe so the chevron clears the notch on
       iPhones with Dynamic Island. -->
  <a
    href="/login"
    aria-label="Back to sign in"
    class="absolute left-3 top-3 z-20 inline-flex items-center gap-1 rounded-full px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted/40 hover:text-foreground pt-safe"
  >
    <ChevronLeft class="size-4" />
    Back
  </a>

  <div class="relative z-10 flex w-full max-w-sm flex-col items-center">
    <!-- Brand mark hero — same SVG composition as /login so the brand
         identity reads continuously across the auth flow. -->
    <div
      class="mb-7 flex size-16 items-center justify-center"
      style="filter: drop-shadow(0 6px 24px rgba(139, 92, 246, 0.35)) drop-shadow(0 1px 2px rgba(0, 0, 0, 0.25));"
      aria-hidden="true"
    >
      <svg width="64" height="64" viewBox="0 0 1024 1024">
        <defs>
          <linearGradient id="signup-bg" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="#6366f1" />
            <stop offset="55%" stop-color="#8b5cf6" />
            <stop offset="100%" stop-color="#a855f7" />
          </linearGradient>
        </defs>
        <rect width="1024" height="1024" rx="232" fill="url(#signup-bg)" />
        <rect x="0" y="0" width="1024" height="512" rx="232" fill="#ffffff" opacity="0.06" />
        <g
          transform="translate(192,192) scale(26.667)"
          fill="none"
          stroke="#ffffff"
          stroke-width="1.8"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
          <path
            d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09"
          />
          <path
            d="M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z"
          />
          <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05" />
        </g>
      </svg>
    </div>

    <h1 class="text-center text-3xl font-semibold tracking-tight">
      {data.isFirstUser ? `Welcome to ${APP_NAME}` : 'Set up your account'}
    </h1>
    <p class="mt-2 text-center text-sm text-muted-foreground">
      {#if data.isFirstUser}
        The first account becomes the workspace owner. You can invite others later from Settings.
      {:else}
        Use your invite code to claim a seat. You'll set up a passkey so sign-in is instant next
        time.
      {/if}
    </p>

    {#if error}
      <div
        class="mt-6 flex w-full items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200"
        role="alert"
      >
        <AlertCircle class="mt-0.5 size-4 flex-shrink-0" />
        <span class="leading-relaxed">{error}</span>
      </div>
    {/if}

    <!-- Card wrapping the form. Same glassy aesthetic as /login so the
         user feels like they're filling out a form inside the same
         surface, not arriving at a totally new screen. -->
    <form
      class="mt-6 w-full rounded-2xl border border-border/40 bg-card/60 p-5 shadow-2xl backdrop-blur-xl"
      onsubmit={(e) => {
        e.preventDefault();
        createAccount();
      }}
    >
      <div class="grid gap-4">
        {#if !data.isFirstUser}
          <div class="grid gap-1.5">
            <Label for="invite" class="text-xs uppercase tracking-wide text-muted-foreground"
              >Invite code</Label
            >
            <Input
              id="invite"
              bind:value={inviteCode}
              maxlength={6}
              inputmode="numeric"
              pattern="\d{6}"
              placeholder="123456"
              autocomplete="one-time-code"
              disabled={busy}
              class="h-12 text-center font-mono text-lg tracking-[0.5em]"
            />
          </div>
        {/if}

        <div class="grid gap-1.5">
          <Label for="name" class="text-xs uppercase tracking-wide text-muted-foreground"
            >Name</Label
          >
          <Input
            id="name"
            bind:value={name}
            placeholder="Alice Johnson"
            autocomplete="name"
            disabled={busy}
            class="h-12"
          />
        </div>

        <div class="grid gap-1.5">
          <Label for="email" class="text-xs uppercase tracking-wide text-muted-foreground"
            >Email</Label
          >
          <Input
            id="email"
            type="email"
            bind:value={email}
            placeholder="you@example.com"
            autocomplete="email"
            disabled={busy}
            class="h-12"
          />
        </div>

        <Button
          type="submit"
          disabled={busy}
          class="mt-2 h-12 w-full justify-center gap-2 bg-gradient-to-r from-indigo-500 via-violet-500 to-fuchsia-500 font-medium text-white shadow-lg shadow-violet-500/25 transition-all hover:shadow-violet-500/40 disabled:opacity-60"
        >
          <KeyRound class="size-4" />
          {busy ? 'Setting up…' : 'Create account & set up passkey'}
        </Button>
      </div>
    </form>

    <!-- Trust reassurance — matches /login -->
    <div
      class="mt-6 flex items-center gap-2 rounded-full bg-emerald-500/8 px-3 py-1.5 text-[11px] text-emerald-300/80"
    >
      <ShieldCheck class="size-3.5" />
      <span>Passkeys, end-to-end. No passwords stored.</span>
    </div>

    <!-- Secondary navigation: already-have-account link sits at the
         bottom so it doesn't compete with the primary action above. -->
    <p class="mt-6 text-xs text-muted-foreground">
      Already have an account?
      <a href="/login" class="text-foreground underline-offset-4 hover:underline">Sign in</a>
    </p>
  </div>
</main>
