import { BRAND } from '$lib/client/brand';

/**
 * Storage identifiers for the developer-tools opt-in. Kept OUT of brand.ts
 * (which is fully auto-generated by apply-brand and would drop hand edits) but
 * still derived from BRAND.name, so a rebrand carries them and nothing is
 * hardcoded. Shared by the client module + the SSR gate (hence no runes / no
 * browser APIs here).
 *
 *   - DEVTOOLS_STORAGE_KEY -> localStorage, read by the client button gate
 *   - DEVTOOLS_COOKIE       -> cookie, read by the SSR route gates
 */
export const DEVTOOLS_STORAGE_KEY = `${BRAND.name}:devtools`;
export const DEVTOOLS_COOKIE = `${BRAND.name}-devtools`;
