#!/usr/bin/env node
// verify-no-slop.mjs - block accidental re-introduction of "AI slop" telltales.
//
// "Slop" here is the cluster of typographic + lexical tells that LLM-generated
// prose carries by default and that get progressively scrubbed out of a
// human-edited document. The most reliable one is the en-/em-dash: GPT-style
// models emit U+2013 / U+2014 freely; humans typing on a US keyboard reach for
// the hyphen-minus.
//
// Scan scope (markdown + comment-only for code):
//   - Every tracked .md (full body outside fenced code)
//   - .ts / .tsx / .svelte / .mjs / .js / .cjs -- inside comments only
//     (whole-line // + JSDoc continuation * + multi-line /* */ + trailing //)
//   - .py / .rb / .sh / .bash -- inside # comments only
//   - .yml / .yaml -- inside # whole-line comments only
//
// UI strings, JSX/template content, string literals, and YAML string values
// are LEFT ALONE -- only prose / comment text is checked.
//
// Allowed exceptions:
//   - Em-dashes inside fenced code blocks in .md (literal code)
//   - Em-dashes in CHANGELOG.md (auto-generated by release-please)
//   - User-personal scratchpads (STATE.md, TODO*.md)
//   - The verifier itself (regex literals must contain the codepoints it bans)
//
// Usage:
//   node scripts/system/verify-no-slop.mjs
//
// Exit codes:
//   0 = clean
//   1 = found em-/en-dashes outside the allowed contexts
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

const SCAN_GLOBS = [
  // Markdown -- full body outside fences
  /^modes\/.*\.md$/,
  /^docs\/.*\.md$/,
  /^branding\/.*\.md$/,
  /^\.github\/.*\.md$/,
  /^[A-Z][A-Z_]*\.md$/,
  /^templates\/README\.md$/,
  /^ui\/README\.md$/,
  /^ui\/e2e\/README\.md$/,
  // Code -- comment-only scan
  /^scripts\/.*\.(mjs|js|cjs|sh|bash|py|rb)$/,
  /^ui\/src\/.*\.(ts|tsx|svelte|mjs|js|cjs)$/,
  /^ui\/electron\/src\/.*\.(ts|js|mjs|cjs)$/,
  // YAML
  /^\.github\/workflows\/.*\.ya?ml$/,
  /^lefthook\.yml$/,
];

const SKIP = new Set([
  'CHANGELOG.md',
  'STATE.md',
  'TODO.md',
  'TODO2.md',
  'ui/TODO.md',
  // The verifier itself documents the em-dash codepoints it bans.
  'scripts/system/verify-no-slop.mjs',
]);

function listTrackedFiles() {
  return execSync('git ls-files -z', { cwd: ROOT, encoding: 'buffer' })
    .toString('utf8')
    .split('\0')
    .filter(Boolean);
}

function shouldScan(rel) {
  if (SKIP.has(rel)) return false;
  return SCAN_GLOBS.some((re) => re.test(rel));
}

const DASH_RE = /[–—]/;

// ── Markdown ──────────────────────────────────────────────────────
export function findOffendersMd(text) {
  const lines = text.split('\n');
  const offenders = [];
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    if (/^\s*```/.test(lines[i])) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (DASH_RE.test(lines[i])) offenders.push({ line: i + 1, text: lines[i].trim() });
  }
  return offenders;
}

// ── TS / JS / Svelte (comment-only) ──────────────────────────────
export function findOffendersTs(text) {
  const lines = text.split('\n');
  const offenders = [];
  let inBlock = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const opens = (line.match(/\/\*/g) || []).length;
    const closes = (line.match(/\*\//g) || []).length;

    const isPureComment =
      /^\s*\/\//.test(line) || /^\s*\*(?:\s|$|\/)/.test(line) || /^\s*\/\*+/.test(line);

    if ((inBlock || isPureComment) && DASH_RE.test(line)) {
      offenders.push({ line: i + 1, text: line.trim() });
    } else if (line.includes('//')) {
      // Trailing comment heuristic
      const m = line.match(/^(.*?)(\s+\/\/(?!\/).*)$/);
      if (m) {
        const before = m[1];
        const comment = m[2];
        const isUrl = before.length > 0 && before[before.length - 1] === ':';
        const stripped = before.replace(/\\./g, '');
        const insideString =
          (stripped.match(/"/g) || []).length % 2 === 1 ||
          (stripped.match(/'/g) || []).length % 2 === 1 ||
          (stripped.match(/`/g) || []).length % 2 === 1;
        if (!isUrl && !insideString && DASH_RE.test(comment)) {
          offenders.push({ line: i + 1, text: line.trim() });
        }
      }
    }

    if (opens > closes) inBlock = true;
    if (closes >= opens && inBlock && closes > 0) inBlock = false;
  }
  return offenders;
}

// ── Python / Ruby / Shell (comment-only) ─────────────────────────
export function findOffendersHash(text) {
  const lines = text.split('\n');
  const offenders = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*#/.test(line) && DASH_RE.test(line)) {
      offenders.push({ line: i + 1, text: line.trim() });
    } else if (line.includes('#')) {
      const m = line.match(/^(.*?)(\s+#.*)$/);
      if (m) {
        const before = m[1];
        const comment = m[2];
        const stripped = before.replace(/\\./g, '');
        const insideString =
          (stripped.match(/"/g) || []).length % 2 === 1 ||
          (stripped.match(/'/g) || []).length % 2 === 1;
        if (!insideString && DASH_RE.test(comment)) {
          offenders.push({ line: i + 1, text: line.trim() });
        }
      }
    }
  }
  return offenders;
}

// ── YAML (whole-line # comments only) ────────────────────────────
export function findOffendersYaml(text) {
  const lines = text.split('\n');
  const offenders = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*#/.test(line) && DASH_RE.test(line)) {
      offenders.push({ line: i + 1, text: line.trim() });
    }
  }
  return offenders;
}

function pickScanner(rel) {
  if (/\.md$/.test(rel)) return findOffendersMd;
  if (/\.(ts|tsx|svelte|mjs|js|cjs)$/.test(rel)) return findOffendersTs;
  if (/\.(py|rb|sh|bash)$/.test(rel)) return findOffendersHash;
  if (/\.ya?ml$/.test(rel)) return findOffendersYaml;
  return null;
}

// Run as script (not as imported module).
if (import.meta.url === `file://${process.argv[1]}`) {
  const tracked = listTrackedFiles();
  const targets = tracked.filter(shouldScan);

  let total = 0;
  const reports = [];
  for (const rel of targets) {
    let body;
    try {
      body = readFileSync(join(ROOT, rel), 'utf8');
    } catch {
      continue;
    }
    const fn = pickScanner(rel);
    if (!fn) continue;
    const offenders = fn(body);
    if (offenders.length) {
      total += offenders.length;
      reports.push({ rel, offenders });
    }
  }

  if (total === 0) {
    console.log(`OK verify-no-slop - ${targets.length} file(s) scanned, 0 em-/en-dashes in scope.`);
    process.exit(0);
  }

  console.error('');
  console.error(
    `FAIL verify-no-slop - ${total} offending line(s) across ${reports.length} file(s):`,
  );
  console.error('');
  for (const { rel, offenders } of reports.slice(0, 30)) {
    for (const { line, text } of offenders.slice(0, 5)) {
      console.error(`  ${rel}:${line}  ${text.slice(0, 100)}`);
    }
  }
  if (reports.length > 30) console.error(`  ... and ${reports.length - 30} more file(s)`);
  console.error('');
  console.error('Em-/en-dashes flagged in prose/comment contexts. Replace U+2014 with -- and');
  console.error('U+2013 with - . String literals + UI text are exempt by design.');
  process.exit(1);
}
