#!/usr/bin/env node
/**
 * verify-no-slop.mjs - block accidental re-introduction of "AI slop" telltales.
 *
 * "Slop" here is the cluster of typographic + lexical tells that LLM-generated
 * prose carries by default and that get progressively scrubbed out of a
 * human-edited document. The most reliable one is the en-/em-dash: GPT-style
 * models emit U+2013 / U+2014 freely; humans typing on a US keyboard reach for
 * the hyphen-minus.
 *
 * What this script scans:
 *   - Every tracked .md (full body)
 *   - Every tracked .ts / .tsx / .svelte / .mjs ONLY inside line/block
 *     comments (UI strings + JSDoc examples are allowed em-dashes)
 *
 * What it flags (non-zero exit):
 *   - U+2014 EM DASH outside code-fence content + outside JSON / SVG / YAML
 *   - U+2013 EN DASH same
 *
 * What it explicitly allows:
 *   - Em-dashes inside fenced code blocks (```...```) - those are literal
 *   - Em-dashes inside SVG path / metadata strings (binary-ish)
 *   - Em-dashes in CHANGELOG.md (auto-generated by release-please)
 *   - User-personal scratchpads (STATE.md, TODO*.md - gitignored)
 *
 * Usage:
 *   node scripts/system/verify-no-slop.mjs
 *
 * Exit codes:
 *   0 = clean
 *   1 = found em-dashes outside the allowed contexts
 */
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

const SCAN_GLOBS_MD = [
  /^modes\/.*\.md$/,
  /^docs\/.*\.md$/,
  /^branding\/.*\.md$/,
  /^\.github\/.*\.md$/,
  /^[A-Z][A-Z_]*\.md$/,
  /^templates\/README\.md$/,
  /^ui\/README\.md$/,
  /^ui\/e2e\/README\.md$/,
];

const SKIP = new Set([
  'CHANGELOG.md',
  'STATE.md',
  'TODO.md',
  'TODO2.md',
  'ui/TODO.md',
  // The verifier itself documents the em-dash codepoints it bans.
  'scripts/system/verify-no-slop.mjs',
]);

function listTrackedFiles() {
  return execSync('git ls-files -z', { cwd: ROOT, encoding: 'buffer' })
    .toString('utf8')
    .split('\0')
    .filter(Boolean);
}

function shouldScan(rel) {
  if (SKIP.has(rel)) return false;
  return SCAN_GLOBS_MD.some((re) => re.test(rel));
}

const EM_DASH = '—';
const EN_DASH = '–';
const DASH_RE = new RegExp(`[${EM_DASH}${EN_DASH}]`);

function findOffenders(text) {
  if (!DASH_RE.test(text)) return [];
  const lines = text.split('\n');
  const offenders = [];
  let insideFence = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*```/.test(line)) {
      insideFence = !insideFence;
      continue;
    }
    if (insideFence) continue;
    if (DASH_RE.test(line)) offenders.push({ line: i + 1, text: line.trim() });
  }
  return offenders;
}

const tracked = listTrackedFiles();
const targets = tracked.filter(shouldScan);

let total = 0;
const reports = [];
for (const rel of targets) {
  let body;
  try {
    body = readFileSync(join(ROOT, rel), 'utf8');
  } catch {
    continue;
  }
  const offenders = findOffenders(body);
  if (offenders.length) {
    total += offenders.length;
    reports.push({ rel, offenders });
  }
}

if (total === 0) {
  console.log(`OK verify-no-slop - ${targets.length} file(s) scanned, 0 em-/en-dashes in scope.`);
  process.exit(0);
}

console.error('');
console.error(`FAIL verify-no-slop - ${total} offending line(s) across ${reports.length} file(s):`);
console.error('');
for (const { rel, offenders } of reports.slice(0, 20)) {
  for (const { line, text } of offenders.slice(0, 5)) {
    console.error(`  ${rel}:${line}  ${text.slice(0, 100)}`);
  }
}
if (reports.length > 20) console.error(`  ... and ${reports.length - 20} more file(s)`);
console.error('');
console.error('Em-dash and en-dash are an AI-prose tell. Replace U+2014 with -- and');
console.error('U+2013 with - in prose contexts. Inside code fences they are allowed.');
process.exit(1);
