// AUTO-GENERATED by scripts/native/apply-brand.mjs -- do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

/** Brand constants for the Electron main process. */
export const BRAND = {
  name: "heron",
  displayName: "Heron",
  bundleId: "com.resistjs.heron",
  urlScheme: "heron",
  serviceType: "_heron._tcp",
  mdnsType: "heron",
  repoUrl: "https://github.com/kaelys-js/heron",
  issuesUrl: "https://github.com/kaelys-js/heron/issues",
  homepageUrl: "https://heron.app",
  copyright: "© 2026 Heron contributors (original work © 2026 santifer). Licensed under the MIT License.",
} as const;
