// AUTO-GENERATED by scripts/native/apply-brand.mjs — do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

/** Brand constants for the Electron main process. */
export const BRAND = {
  name: "career-ops",
  displayName: "Career Ops",
  bundleId: "com.resistjs.careerops",
  urlScheme: "careerops",
  serviceType: "_career-ops._tcp",
  mdnsType: "career-ops",
  repoUrl: "https://github.com/kaelys-js/career-ops",
  issuesUrl: "https://github.com/kaelys-js/career-ops/issues",
} as const;
