// AUTO-GENERATED by scripts/native/apply-brand.mjs — do not edit.
// Edit branding/brand.json and run `pnpm brand:apply`.

/** Brand constants for the Electron main process. */
export const BRAND = {
  name: "heron",
  displayName: "Heron",
  bundleId: "com.heron.app",
  urlScheme: "heron",
  serviceType: "_heron._tcp",
  mdnsType: "heron",
  repoUrl: "https://github.com/heron/heron",
  issuesUrl: "https://github.com/heron/heron/issues",
} as const;
