/** System tray / macOS Menu Bar. Context menu carries live stats
 *  (queued / applied / upcoming), section deep-links, scan/autopilot
 *  controls, window actions, macOS Menu-Bar-Only toggle. macOS title
 *  + Dock badge mirror the queued / upcoming counts; polls /api/stats
 *  every 30s with "(backend offline)" fallback. */
import { Tray, Menu, nativeImage, app, BrowserWindow } from 'electron';
import path from 'node:path';
import { existsSync, rmSync, writeFileSync, watch } from 'node:fs';
import type { FSWatcher } from 'node:fs';
import { BRAND } from './brand';
import { fetchStats } from './tray-http';
import type { Stats } from './tray-http';
import { buildTrayMenuTemplate, computeTrayTitle, computeDockBadge } from './tray-menu-builder';

export type TrayHandlers = {
  getBackendUrl: () => string;
  onOpen: () => void;
  onQuit: () => void;
  /** Bring the main window to front and navigate to a path. */
  onOpenPath?: (path: string) => void;
  /** Toggle Dock icon visibility (macOS). When `hideDock` is true the
   *  app becomes a pure menu-bar utility. */
  onSetDockVisible?: (visible: boolean) => void;
};

const POLL_INTERVAL_MS = 30_000;

/**
 * Electron tray menu controller. Class name is brand-agnostic
 * (DesktopTray, not HeronTray) so a rebrand doesn't require an
 * Xcode-style class rename across every importer.
 */
export class DesktopTray {
  private tray?: Tray;
  private timer?: NodeJS.Timeout;
  private iconWatcher?: FSWatcher;
  private stats: Stats | null = null;
  private handlers: TrayHandlers;
  private menuBarOnly = false;

  constructor(handlers: TrayHandlers) {
    this.handlers = handlers;
    // Restore the user's "Menu Bar Only" preference. Stored in a file so
    // it survives across launches; we don't pull in electron-store for one
    // boolean.
    try {
      const pref = path.join(app.getPath('userData'), 'menubar-only.pref');
      this.menuBarOnly = existsSync(pref);
    } catch {
      /* default: false */
    }
  }

  /** Absolute path to the menu-bar icon (build/tray.png -- the BARE mascot, no
   *  squircle, generated by generate-icons.mjs). */
  private iconPath(): string {
    return path.resolve(__dirname, '..', '..', 'build', 'tray.png');
  }

  /** Load + size the tray image. We deliberately do NOT mark it a macOS
   *  template image: a template renders as a flat monochrome silhouette,
   *  hiding the mascot; a normal (colour) image shows the actual mascot.
   *  22px is the macOS menu-bar standard; Windows accepts anything. */
  private loadTrayImage(): Electron.NativeImage {
    return nativeImage.createFromPath(this.iconPath()).resize({ width: 22, height: 22 });
  }

  start(): void {
    this.tray = new Tray(this.loadTrayImage());
    this.tray.setToolTip(BRAND.displayName);
    // Single-click on the tray icon brings the window forward on
    // Windows + Linux. macOS opens the menu via the right-click handler.
    this.tray.on('click', () => {
      if (process.platform !== 'darwin') {
        this.handlers.onOpen();
      }
    });
    this.tray.on('right-click', () => this.tray?.popUpContextMenu());

    // Apply persisted menu-bar-only state.
    if (this.menuBarOnly) {
      this.setMenuBarOnly(true);
    }

    this.refresh();
    this.timer = setInterval(() => void this.refresh(), POLL_INTERVAL_MS);

    // Keep the Show/Hide Window label honest: rebuild the menu whenever a
    // window's visibility changes, so the macOS left-click menu (set via
    // setContextMenu) reflects the live state, not the last poll.
    for (const w of BrowserWindow.getAllWindows()) {
      w.on('show', () => this.rebuildMenu());
      w.on('hide', () => this.rebuildMenu());
    }

    this.watchTrayIcon();
  }

  /** Dev-only HMR for the menu-bar icon: when `pnpm dev`'s brand-watcher
   *  regenerates build/tray.png, re-apply it live so the new mascot shows
   *  WITHOUT restarting Electron (vite HMR only reloads the WebView, never the
   *  main process). Watch the build DIRECTORY -- watching the file inode breaks
   *  on the atomic replace generate-icons does. No-op in packaged builds. */
  private watchTrayIcon(): void {
    if (app.isPackaged) {
      return;
    }
    try {
      this.iconWatcher = watch(path.dirname(this.iconPath()), (_event, file) => {
        if (file === 'tray.png' && this.tray) {
          this.tray.setImage(this.loadTrayImage());
        }
      });
    } catch {
      /* file watching is a dev convenience; ignore failures */
    }
  }

  /** True if any (non-destroyed) app window is currently visible. */
  private anyWindowVisible(): boolean {
    return BrowserWindow.getAllWindows().some((w) => !w.isDestroyed() && w.isVisible());
  }

  stop(): void {
    if (this.timer) {
      clearInterval(this.timer);
    }
    this.iconWatcher?.close();
    this.iconWatcher = undefined;
    this.tray?.destroy();
    this.tray = undefined;
  }

  /** Fetch /api/stats and rebuild the popover menu.
   *
   * F18 -- known multi-user limitation: this fetch runs from the Electron
   * main process which has NO Better-Auth cookie + NO bearer token (the
   * WebView holds those). On a multi-user install /api/stats 401s and
   * this returns null. The menu falls back to a generic
   * "Heron is running · open dashboard" state.
   *
   * Proper fix (follow-up): IPC bridge -- the WebView fetches stats
   * inside its authenticated context and pushes them to the main
   * process via `tray:push-stats`. The main process then doesn't need
   * to authenticate at all. Tracked as a Phase 4 follow-up.
   *
   * Until then: the tray gracefully degrades (no stats != crash).
   */
  private async refresh(): Promise<void> {
    const url = this.handlers.getBackendUrl();
    // fetchStats() is defensively try/catched -- it always resolves
    // (never rejects), returning null on failure. No outer .catch needed.
    this.stats = await fetchStats(url);
    this.rebuildMenu();
    this.updateDockBadge();
  }

  private rebuildMenu(): void {
    if (!this.tray) {
      return;
    }
    const items = buildTrayMenuTemplate(
      {
        platform: process.platform,
        menuBarOnly: this.menuBarOnly,
        windowVisible: this.anyWindowVisible(),
        appVersion: app.getVersion(),
        displayName: BRAND.displayName,
      },
      {
        onToggleWindow: () => this.toggleWindow(),
        onToggleMenuBarOnly: () => this.setMenuBarOnly(!this.menuBarOnly),
        onQuit: () => this.handlers.onQuit(),
      },
    );

    const contextMenu = Menu.buildFromTemplate(items);
    this.tray.setContextMenu(contextMenu);

    // macOS title -- show queued count as a number badge next to the
    // tray icon when > 0. This is the equivalent of an unread badge for
    // a menu bar app.
    this.tray.setTitle(computeTrayTitle(this.stats, process.platform));
  }

  /** macOS / Linux Dock badge -- set to the upcoming-interviews count so
   *  glancing at the Dock shows "you have N interviews coming up". */
  private updateDockBadge(): void {
    if (process.platform !== 'darwin') {
      return;
    }
    if (!app.dock) {
      return;
    }
    app.dock.setBadge(computeDockBadge(this.stats, process.platform));
  }

  /** Show the window if it's hidden, hide it if any window is visible. The
   *  label "Show / Hide Window" is static; the action resolves the right
   *  direction from the live visibility state at click time. */
  private toggleWindow(): void {
    const wins = BrowserWindow.getAllWindows();
    if (wins.some((w) => w.isVisible())) {
      wins.forEach((w) => w.hide());
    } else {
      this.handlers.onOpen();
    }
  }

  /** Toggle macOS Dock visibility. When hidden, Heron becomes a
   *  pure menu bar app -- close-window doesn't quit, the icon never
   *  appears in the Dock, and Cmd+Tab skips it. Re-show by re-toggling
   *  from the tray menu. */
  private setMenuBarOnly(enable: boolean): void {
    if (process.platform !== 'darwin' || !app.dock) {
      return;
    }
    this.menuBarOnly = enable;
    try {
      if (enable) {
        void app.dock.hide();
      } else {
        void app.dock.show();
      }
      this.handlers.onSetDockVisible?.(!enable);
      // Persist the preference.
      const pref = path.join(app.getPath('userData'), 'menubar-only.pref');
      if (enable) {
        writeFileSync(pref, '1');
      } else {
        rmSync(pref, { force: true });
      }
    } catch {
      /* non-fatal */
    }
    this.rebuildMenu();
  }
}
