import { listInvitesFromOwner, userCount } from '$lib/server/invite-codes';
import { authDb } from '$lib/server/db';
import { users } from '$lib/server/db/auth-schema';
import { requireUserId, hasAdmin } from '$lib/server/auth-helpers';
import { isNull } from 'drizzle-orm';

/**
 * Settings → Users — household / team admin.
 *
 * Visibility rules (RBAC):
 *   • Members: see only their own row (email, role, joined-at). They can
 *     still see their own outstanding invite codes — but listInvitesFromOwner
 *     is scoped by owner_user_id so they only see codes they personally
 *     generated.
 *   • Owners and admins: see every active user on the install.
 *
 * The page itself doesn't expose promotion/demotion controls yet (Phase 4+);
 * for now this is a read-only "household roster". The crucial property
 * is that members can't enumerate other users' emails.
 */
export async function load({ locals }: { locals: App.Locals }) {
  const userId = requireUserId(locals);
  const canSeeAll = hasAdmin(locals);
  const rows = canSeeAll
    ? authDb
        .select({
          id: users.id,
          email: users.email,
          name: users.name,
          role: users.role,
          createdAt: users.createdAt,
        })
        .from(users)
        .where(isNull(users.deletedAt))
        .all()
    : authDb
        .select({
          id: users.id,
          email: users.email,
          name: users.name,
          role: users.role,
          createdAt: users.createdAt,
        })
        .from(users)
        .where(isNull(users.deletedAt))
        .all()
        .filter((u) => u.id === userId);

  // listInvitesFromOwner only returns codes generated BY the calling
  // user — the underlying SQL is `WHERE owner_user_id = ?`, so a member
  // can't see invites issued by the owner.
  const invites = listInvitesFromOwner(userId);
  return {
    me: locals.user!,
    canSeeAll,
    users: rows.map((u) => ({
      id: u.id,
      email: u.email,
      name: u.name,
      role: u.role,
      createdAt: typeof u.createdAt === 'number' ? u.createdAt : new Date(u.createdAt).getTime(),
      isMe: u.id === userId,
    })),
    invites,
    totalUsers: canSeeAll ? userCount() : 1,
  };
}
