/** electron-rt.test -- Capacitor-scaffolded preload bridge. The source
 *  is regenerated by `npx cap copy electron` so we don't write tests
 *  that mock its internals; we only pin the `contextBridge.exposeInMainWorld`
 *  call at the bottom, which is the contract we depend on regardless of
 *  Capacitor's regeneration. Source is excluded from coverage; see
 *  vitest.config.ts header for why. */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const __exposeInMainWorld = vi.fn();
const __ipcRendererInvoke = vi.fn();
const __ipcRendererSend = vi.fn();
const __ipcRendererAddListener = vi.fn();
const __ipcRendererRemoveListener = vi.fn();

vi.mock('electron', () => ({
  contextBridge: { exposeInMainWorld: __exposeInMainWorld },
  ipcRenderer: {
    invoke: __ipcRendererInvoke,
    send: __ipcRendererSend,
    addListener: __ipcRendererAddListener,
    removeListener: __ipcRendererRemoveListener,
  },
}));

beforeEach(() => {
  __exposeInMainWorld.mockReset();
  __ipcRendererInvoke.mockReset();
  __ipcRendererSend.mockReset();
  __ipcRendererAddListener.mockReset();
  __ipcRendererRemoveListener.mockReset();
  vi.resetModules();
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe('electron-rt -- module-load behaviour', () => {
  it('exposes CapacitorCustomPlatform via contextBridge', async () => {
    await import('./electron-rt.js');
    expect(__exposeInMainWorld).toHaveBeenCalledTimes(1);
    const [name, payload] = __exposeInMainWorld.mock.calls[0];
    expect(name).toBe('CapacitorCustomPlatform');
    expect(payload.name).toBe('electron');
    expect(typeof payload.plugins).toBe('object');
  });

  it('plugins object is initialised (matches the empty-plugins state from Capacitor scaffold)', async () => {
    await import('./electron-rt.js');
    const payload = __exposeInMainWorld.mock.calls[0][1];
    // electron-plugins.js currently exports `{}` -- contextApi stays empty.
    // Test pins THIS contract; when a real Capacitor plugin lands, the
    // shape of `plugins` will widen and this test will be widened with it.
    expect(payload.plugins).toEqual({});
  });

  it('does not call ipcRenderer.invoke/send at module load (no plugin classes yet)', async () => {
    await import('./electron-rt.js');
    expect(__ipcRendererInvoke).not.toHaveBeenCalled();
    expect(__ipcRendererSend).not.toHaveBeenCalled();
  });
});
