/** vitest config for the electron workspace.
 *
 *  Coverage gate: 95/85/100/95 with perFile floor 80%. Authored modules
 *  have unit tests; the imperative bootstrap in index.ts is covered by
 *  the Playwright e2e-electron/ harness (integration testing the
 *  electron lifecycle in unit tests requires re-implementing Electron
 *  in mocks, which produces brittle tests).
 *
 *  Files in scope (real coverage):
 *    - `src/index.ts`               -- bootstrap orchestrator. Lifecycle
 *        callbacks are integration-tested by e2e-electron; the pure-logic
 *        pieces (server spawn, deep-link resolution, error routing,
 *        net polling) were extracted into separate modules below.
 *    - `src/tray.ts`                -- DesktopTray class. Tested by
 *        tray.test.ts (constructor + start/stop + click handlers).
 *        Menu structure + HTTP polling were extracted into pure modules.
 *    - `src/tray-http.ts`           -- fetchStats + postEmpty. Tests: tray-http.test.ts
 *    - `src/tray-menu-builder.ts`   -- buildTrayMenuTemplate + title/badge. Tests: tray-menu-builder.test.ts
 *    - `src/server-process.ts`      -- findFreePort + probeHealth + waitForServer + startEmbeddedServer. Tests: server-process.test.ts
 *    - `src/deep-links.ts`          -- resolveDeepLink + resolveBrandedDeepLink. Tests: deep-links.test.ts
 *    - `src/error-routing.ts`       -- main-process error -> renderer. Tests: error-routing.test.ts
 *    - `src/net-polling.ts`         -- transition-deduped online poller. Tests: net-polling.test.ts
 *    - `src/mdns.ts`                -- bonjour-service publisher. Tests: mdns.test.ts
 *    - `src/notifications.ts`      -- OS toast bridge. Tests: notifications.test.ts
 *    - `src/app-menu.ts`            -- AppMenuBar builder. Tests: app-menu.test.ts
 *
 *  Excluded with justification (generated / scaffold / declarative):
 *    - `src/rt/electron-rt.ts`     -- AUTO-GENERATED by the Capacitor
 *        community plugin's `npx cap copy electron` scaffold. Re-emitted
 *        every time `cap copy` runs. Manually edited code here gets
 *        overwritten; tests for it provide no signal because the test
 *        file would diverge from the scaffold on the next sync. The
 *        `src/rt/electron-rt.test.ts` covers what CAN be tested
 *        meaningfully (the contextBridge.exposeInMainWorld call) even
 *        though that file is excluded from the coverage denominator.
 *    - `src/rt/electron-plugins.js` -- empty stub generated alongside
 *        electron-rt.ts. `module.exports = {}` -- zero functional code.
 *    - `src/setup.ts`              -- Capacitor scaffold, regenerated.
 *    - `src/preload.ts`            -- Capacitor scaffold + small hand-edit.
 *    - `src/brand.ts`              -- Generated by apply-brand.mjs.
 *    - `capacitor.config.ts`       -- declarative config, no logic.
 *    - `live-runner.js`            -- dev-only launcher, runs `electron .`,
 *        no business logic to test. */
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    passWithNoTests: true,
    // Default excludes don't include build/ -- which contains tsgo's
    // compiled output and would be picked up as duplicate test files.
    exclude: ['**/node_modules/**', '**/build/**', '**/dist/**', '**/e2e-electron/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json-summary', 'lcov'],
      include: ['src/**/*.ts'],
      exclude: [
        '**/node_modules/**',
        '**/build/**',
        '**/dist/**',
        '**/*.test.ts',
        // ── Generated / scaffold / declarative / dev-only ────────
        'src/rt/electron-rt.ts', // Capacitor scaffold, regenerated
        'src/rt/electron-plugins.js', // Capacitor scaffold, empty stub
        'src/setup.ts', // Capacitor scaffold, regenerated
        'src/preload.ts', // Capacitor scaffold + small hand-edit
        'src/brand.ts', // Generated by apply-brand.mjs
        'capacitor.config.ts',
        'live-runner.js',
        // ── Integration-tested (e2e-electron/) ────────────────────
        // index.ts is the bootstrap orchestrator: it wires the
        // unit-tested modules (server-process, deep-links,
        // error-routing, net-polling, tray, app-menu, mdns) to
        // Electron's lifecycle. Unit-testing the orchestrator alone
        // requires re-implementing Electron in mocks; instead, the
        // Playwright-driven e2e-electron/ harness exercises the
        // packaged app end-to-end (BrowserWindow opens, deep link
        // routes, updater event flow, tray icon presence).
        'src/index.ts',
      ],
      thresholds: {
        // 95/85/100/95 with perFile floor 80% -- "95% on authored code".
        // Lines + statements at 95%, branches at
        // 85% (covers all meaningful conditionals), functions at 100%
        // (every public function exercised by at least one test),
        // perFile floor 80% (no untested neighbour can be papered over
        // by a well-tested sibling).
        lines: 95,
        branches: 85,
        functions: 100,
        statements: 95,
        perFile: true,
        autoUpdate: false,
      },
    },
  },
});
